eth:
  outputs:
    ci:
      account: FIPPPAO-ES17205
      database: CI
      private_key_path: "{{env_var('DBT_PRIVATE_KEY_PATH')}}"
      role: ACCOUNTADMIN
      schema: CI_schema
      threads: 1
      type: snowflake
      user: wareine
      warehouse: compute_wh
  target: ci
