version: 2

models:
  - name: stg_transactions
    description: Transactions in the ethereum blockchain
    columns:
      - name: hash
        description: > 
          This is a very long multiline description about unique 
          identifier of each transaction in the ethereum blockchain
        data_tests:
          - unique
          - not_null
  - name: stablecoin_activity_per_day
    config:
      contract:
        enforced: true
        alias_type: true
    columns:
      - name: date
        data_type: date
        description: ""

      - name: token_address
        data_type: varchar
        description: ""

      - name: type
        data_type: varchar
        description: ""

      - name: symbol
        data_type: varchar
        description: ""

      - name: total_usd_value
        data_type: float
        description: ""
