version: 2

models:
  - name: stg_transactions
    description: Transactions in the ethereum blockchain
    columns:
      - name: hash
        description: > 
          This is a very long multiline description about unique 
          identifier of each transaction in the ethereum blockchain
        data_tests:
          - unique
          - not_null
