version: 2

models:
  - name: stg_transactions
    description: Transactions in the ethereum blockchain
    columns:
      - name: hash
        description: > 
          This is a very long multiline description about unique 
          identifier of each transaction in the ethereum blockchain
        data_tests:
          - unique
          - not_null
  - name: stablecoin_activity_per_day
    lastest_version: 1
    config:
      contract:
        enforced: true
        alias_type: true
    columns:
      - name: date
        data_type: date
        description: ""

      - name: token_address
        data_type: varchar
        description: ""

      - name: type
        data_type: varchar
        description: ""

      - name: symbol
        data_type: varchar
        description: ""

      - name: total_usd_value
        data_type: float
        description: ""
  # Declare the versions, and highlight the diffs
    versions:
    
      - v: 1
        # Matches what's above -- nothing more needed
    
      - v: 2
        # Removed a column -- this is the breaking change!
        columns:
          # This means: use the 'columns' list from above, but exclude country_name
          - include: all
            exclude: [token_address,symbol]